name: tests

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: yarn
          cache-dependency-path: yarn.lock
      - run: yarn
      - run: yarn test
      - name: 'Report Coverage'
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          json-summary-path: '.coverage/coverage-summary.json'
          json-summary-compare-path: '.github/coverage-summary.json'
          file-coverage-mode: 'all'

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: yarn
          cache-dependency-path: yarn.lock
      - run: yarn
      - run: yarn build
      - name: Zip module
        working-directory: ./
        run: zip -r ./module.zip ./dist/*
      - name: upload module
        uses: actions/upload-artifact@v4
        with:
          path: ./module.zip
          name: module-${{ github.head_ref || github.ref_name }}.zip
          retention-days: 7
