name: Mod Builder

on:
  push:
    tag:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Zip Files
        working-directory: ./
        run: zip -r ./module.zip ./* -x "tests/*" -x "*.git*" -x ".husky" -x "playwright.config.ts"

      - name: Create Release
        id: create-release
        uses: ncipollo/release-action@v1.10.0
        with:
          allowUpdates: true
          token: ${{secrets.GITHUB_TOKEN}}
          artifacts: ./module.zip, ./module.json
